"""
AUXETIC SCAFFOLD FEM MODEL - ABAQUS LAUNCHER SCRIPT

    Main generator script for the FEM model defined.

    Must be run in Abaqus/CAE environment, giving externally the design name and its parameters.

    Example command line: abaqus cae noGUI=gen_inp.py -- design a b d xr yr zr id

    The parameters can be read from the .txt file generated by the DESIGN PARAMETERS DEFINITION SCRIPT
    (initial_settings.py) or given directly from the command line.

    Arguments (8):
        - design (string)
        - a (float)
        - b (float)
        - d (float)
        - xr (int)
        - yr (int)
        - zr (int)
        - id (int)

"""

from abaqus import *
from abaqusConstants import *
import sys
import os
import create_aux_str

# ---------------------------------------------------------------
# Create a folder to collect the .inp files:

inp_folder_name = 'inp_files'

inp_path = os.path.abspath(os.getcwd()) + '/' + inp_folder_name

if not os.path.exists(inp_path):
    os.mkdir(inp_folder_name)

os.chdir(inp_path)

# ---------------------------------------------------------------
# Read input arguments:

design_name = sys.argv[-8]

parameters = [float(sys.argv[-7]),  # A
              float(sys.argv[-6]),  # B
              float(sys.argv[-5]),  # D
              int(sys.argv[-4]),  # XR
              int(sys.argv[-3]),  # YR
              int(sys.argv[-2]),  # ZR
              int(sys.argv[-1])  # ID
              ]

# ---------------------------------------------------------------
# Execute the function corresponding to the design:

Mdb()  # Initiates Abaqus

if design_name == 'hcell_uniform':
    create_aux_str.hcell_uniform(*parameters)

elif design_name == 'stri_uniform':
    create_aux_str.stri_uniform(*parameters)

elif design_name == 'stri_shift':
    create_aux_str.stri_shift(*parameters)

elif design_name == 'sreg_uniform':
    create_aux_str.sreg_uniform(*parameters)

elif design_name == 'sreg_shift':
    create_aux_str.sreg_shift(*parameters)

elif design_name == 'sinv_uniform':
    create_aux_str.sinv_uniform(*parameters)

elif design_name == 'sinv_shift':
    create_aux_str.sinv_shift(*parameters)

elif design_name == 'arrowhead':
    create_aux_str.arrowhead(*parameters)

# ---------------------------------------------------------------
